"use client"
import { useEffect, useState } from "react"
import Link from "next/link"
import { API_URL, SITE_URL } from "../../lib/config"

async function iapi(path,opt={}){const res=await fetch(`${API_URL}${path}`,{credentials:"include",headers:{"Content-Type":"application/json",...(opt.headers||{})},...opt}); const j=await res.json().catch(()=>({})); if(!res.ok) throw new Error(j.message||"Failed"); return j}
function money(v){return `RM ${Number(v||0).toFixed(2)}`}
const COPY_LANG={zh:(p,link)=>`这个 ${p.name} 我觉得你可以先看一下👇\n${link}\n佣金/优惠活动可能会变化，详情以页面为准。`,en:(p,link)=>`Take a look at ${p.name} 👇\n${link}\nPromo details may change, please refer to the page.`,ms:(p,link)=>`Boleh tengok ${p.name} dulu 👇\n${link}\nButiran promosi mungkin berubah, rujuk halaman produk.`}
const LABELS={zh:{orders:"查看佣金订单",ref:"你的 ref code",pending:"待结算",confirmed:"已确认",paid:"已付款",count:"订单数",products:"可推广产品",price:"售价",commission:"佣金",preview:"预览",copy:"复制 link",script:"复制推广文案",copied:"已复制"},en:{orders:"Commission Orders",ref:"Your ref code",pending:"Pending",confirmed:"Confirmed",paid:"Paid",count:"Orders",products:"Products to Promote",price:"Price",commission:"Commission",preview:"Preview",copy:"Copy link",script:"Copy promo script",copied:"Copied"},ms:{orders:"Order Komisen",ref:"Kod ref anda",pending:"Menunggu",confirmed:"Disahkan",paid:"Dibayar",count:"Order",products:"Produk Promosi",price:"Harga",commission:"Komisen",preview:"Pratonton",copy:"Salin link",script:"Salin skrip promosi",copied:"Disalin"}}
export default function PromoterHome(){
  const [me,setMe]=useState(null),[products,setProducts]=useState([]),[earn,setEarn]=useState(null),[err,setErr]=useState(""),[copied,setCopied]=useState(""),[lang,setLang]=useState("zh")
  const L=LABELS[lang]||LABELS.zh
  async function load(){try{const [m,p,e]=await Promise.all([iapi('/api/influencer/me'),iapi('/api/influencer/products'),iapi('/api/influencer/earnings')]); setMe(m.influencer); setProducts(p); setEarn(e)}catch(x){setErr(x.message)}}
  useEffect(()=>{load()},[])
  function productLink(slug){return `${SITE_URL || (typeof window!=='undefined'?window.location.origin:'')}/p/${slug}?ref=${me.ref_code}`}
  async function copyLink(slug){const link=productLink(slug); await navigator.clipboard.writeText(link); setCopied(link)}
  async function copyScript(p){const link=productLink(p.slug); const text=(COPY_LANG[lang]||COPY_LANG.zh)(p,link); await navigator.clipboard.writeText(text); setCopied(text)}
  if(err)return <main className="p-10"><Link href="/promoter/login" className="rounded-full bg-slate-950 px-6 py-3 font-black text-white">Promoter Login</Link></main>
  if(!me)return <main className="p-10 font-bold">Loading...</main>
  return <main className="min-h-screen bg-[#f7f4ee] px-4 py-10"><div className="mx-auto max-w-6xl"><section className="rounded-[36px] bg-white p-8 shadow-2xl"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h1 className="text-4xl font-black">{me.name}</h1><p className="mt-2 text-slate-500">{L.ref}：<b>{me.ref_code}</b></p></div><div className="flex flex-wrap gap-2"><button onClick={()=>setLang("zh")} className="rounded-full border px-3 py-2 font-black">中文</button><button onClick={()=>setLang("en")} className="rounded-full border px-3 py-2 font-black">EN</button><button onClick={()=>setLang("ms")} className="rounded-full border px-3 py-2 font-black">BM</button><Link href="/promoter/orders" className="rounded-full bg-slate-950 px-6 py-3 text-center font-black text-white">{L.orders}</Link></div></div><div className="mt-6 grid gap-4 sm:grid-cols-4"><div className="rounded-3xl bg-amber-50 p-5"><b>{L.pending}</b><p className="text-2xl font-black">{money(earn?.pending)}</p></div><div className="rounded-3xl bg-green-50 p-5"><b>{L.confirmed}</b><p className="text-2xl font-black">{money(earn?.confirmed)}</p></div><div className="rounded-3xl bg-blue-50 p-5"><b>{L.paid}</b><p className="text-2xl font-black">{money(earn?.paid)}</p></div><div className="rounded-3xl bg-slate-50 p-5"><b>{L.count}</b><p className="text-2xl font-black">{earn?.orders||0}</p></div></div></section>{copied?<p className="mt-5 rounded-2xl bg-blue-50 p-4 font-bold text-blue-700">{L.copied}：{copied}</p>:null}<h2 className="mt-8 text-3xl font-black">{L.products}</h2><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map(p=><div key={p.id} className="rounded-[28px] bg-white p-5 shadow"><div className="h-44 overflow-hidden rounded-3xl bg-slate-100">{p.image?<img src={p.image} className="h-full w-full object-cover"/>:null}</div><h3 className="mt-4 text-xl font-black">{p.name}</h3><p className="mt-1 text-sm text-slate-500">{p.category} · {p.productType}</p><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-slate-50 p-3"><b>{L.price}</b><p className="font-black">{money(p.price)}</p></div><div className="rounded-2xl bg-amber-50 p-3"><b>{L.commission}</b><p className="font-black">{Number(p.commissionRate||0)}% / {money(p.estimatedCommission)}</p></div></div><div className="mt-4 flex gap-2"><Link href={`/p/${p.slug}?ref=${me.ref_code}`} className="flex-1 rounded-full border px-4 py-3 text-center text-sm font-black">{L.preview}</Link><button onClick={()=>copyLink(p.slug)} className="flex-1 rounded-full bg-slate-950 px-4 py-3 text-sm font-black text-white">{L.copy}</button></div><button onClick={()=>copyScript(p)} className="mt-2 w-full rounded-full bg-amber-500 px-4 py-3 text-sm font-black text-white">{L.script}</button></div>)}</div></div></main>
}
