"use client"
import { useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import { API_URL } from "@/lib/config"
import { authHeaders, clearToken, money } from "@/lib/platformAuth"
export default function MerchantDashboard(){const router=useRouter();const[products,setProducts]=useState([]);const[orders,setOrders]=useState([]);const[error,setError]=useState("");async function load(){try{const [p,o]=await Promise.all([fetch(`${API_URL}/api/merchant/products`,{headers:authHeaders("merchant")}),fetch(`${API_URL}/api/merchant/orders`,{headers:authHeaders("merchant")})]);if(!p.ok||!o.ok)throw new Error("Please login again");setProducts(await p.json());setOrders(await o.json())}catch(e){setError(e.message)}}useEffect(()=>{load()},[]);return <div style={s.page}><Top title="商家后台" logout={()=>{clearToken("merchant");router.push("/merchant/login")}}/><div style={s.grid}><Card title="Products" value={products.length}/><Card title="Orders" value={orders.length}/><Card title="Sales" value={money(orders.filter(o=>o.paymentStatus==="PAID").reduce((a,o)=>a+Number(o.amount||0),0))}/></div><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><button style={s.primary} onClick={()=>router.push("/merchant/products/new")}>+ 上传产品</button><button style={s.primary} onClick={()=>router.push("/merchant/wallet")}>钱包 / 提现</button></div>{error&&<p style={s.error}>{error}</p>}<h2>我的产品</h2><div style={s.cards}>{products.map(p=><div style={s.card} key={p.id}>{p.image&&<img src={p.image} style={s.img}/>}<h3>{p.name}</h3><p>{money(p.price)} · Stock {p.stock}</p><p>Commission: {p.commissionType} {p.commissionValue||p.commissionFixed||0}{p.commissionPercent?` + ${p.commissionPercent}%`:""}</p></div>)}</div><h2>订单</h2><div style={s.table}>{orders.map(o=><div style={s.row} key={o.id}><b>{o.customerName}</b><span>{o.product?.name}</span><span>{money(o.amount)}</span><span>{o.paymentStatus}/{o.shippingStatus}</span></div>)}</div></div>}
function Top({title,logout}){return <div style={s.top}><h1>{title}</h1><button onClick={logout} style={s.ghost}>Logout</button></div>}
function Card({title,value}){return <div style={s.stat}><p>{title}</p><h2>{value}</h2></div>}
const s={page:{padding:24,maxWidth:1100,margin:"0 auto",fontFamily:"Arial"},top:{display:"flex",justifyContent:"space-between",alignItems:"center"},ghost:{border:"1px solid #ddd",background:"white",borderRadius:12,padding:"10px 14px"},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:14},stat:{background:"#111827",color:"white",borderRadius:20,padding:20},primary:{margin:"18px 0",padding:"13px 18px",background:"#2563eb",color:"white",border:0,borderRadius:14,fontWeight:800},cards:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:14},card:{background:"white",border:"1px solid #e5e7eb",borderRadius:18,padding:16},img:{width:"100%",height:150,objectFit:"cover",borderRadius:14},table:{display:"grid",gap:8},row:{display:"grid",gridTemplateColumns:"1.2fr 1.4fr .8fr 1fr",gap:10,background:"#f8fafc",borderRadius:14,padding:12},error:{color:"#b42318"}}
